version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongo_graphql
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    volumes:
      - "graphStore:/data/db"
      - "./db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh"
    ports:
      - 27017-27019:${DB_PORT}
volumes:
  graphStore:
