version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongo_graphql
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: wolftrax
      MONGO_INITDB_ROOT_PASSWORD: wolftrax
    volumes:
      - "graphqlMongo:/data/db"
    ports:
      - 27017:27017
volumes:
  graphqlMongo:
